export const testIds = {
  appConfig: {
    container: 'data-testid ac-container',
    provider: 'data-testid ac-provider',
    openAIKey: 'data-testid ac-openai-api-key',
    customizeOpenAIApiPath: 'data-testid ac-customize-openai-api-path',
    openAIApiPath: 'data-testid ac-openai-api-path',
    openAIOrganizationID: 'data-testid ac-openai-api-organization-id',
    openAIUrl: 'data-testid ac-openai-api-url',
    anthropicKey: 'data-testid ac-anthropic-api-key',
    anthropicUrl: 'data-testid ac-anthropic-api-url',
    vectorEnabled: 'data-testid ac-vector-enabled',
    qdrantAddress: 'data-testid ac-qdrant-address',
    qdrantSecure: 'data-testid ac-qdrant-secure',
    qdrantApiKey: 'data-testid ac-qdrant-api-key',
    grafanaVectorApiUrl: 'data-testid ac-grafana-vector-api-url',
    model: 'data-testid ac-vector-model',
    submit: 'data-testid ac-submit-form',
    basicAuthUsername: 'data-testid ac-basic-auth-username',
    basicAuthPassword: 'data-testid ac-basic-auth-password',
  },
  models: {
    container: 'data-testid models-container',
  },
  mcpTools: {
    container: 'data-testid mcp-tools-container',
    disabled: 'data-testid mcp-tools-disabled',
    loading: 'data-testid mcp-tools-loading',
    error: 'data-testid mcp-tools-error',
    empty: 'data-testid mcp-tools-empty',
    list: 'data-testid mcp-tools-list',
    toolItem: 'data-testid mcp-tools-tool-item',
    toolName: 'data-testid mcp-tools-tool-name',
    toolDescription: 'data-testid mcp-tools-tool-description',
  },
};
