version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/packages/grafana-llm-app"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/packages/grafana-llm-app/llmclient"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"
