name: Test build script
on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true
      - name: Install dependencies
        run: npm ci
      - name: Build plugin
        run: npm run build:all
      - name: Package plugin
        uses: sandersaarond/shared-workflows/actions/package-plugin@package-plugin